name: bukkit showcase

author: Toto Castaldi
website: https://github.com/toto-castaldi/bukkit-plugin-showcase
main: it.toto.minecraft.plugin.ShowCase

commands:
    hello:
        description: Say Hello to everyone!
        usage: /hello

version: 0.1
