name: toto

author: Toto Castaldi
website: https://github.com/toto-castaldi
main: it.toto.minecraft.plugin.CoderDojoPlugin

commands:
    build-a-cube:
        description: Build a Cube
        usage: /build-a-cube width height
    play-a-sound:
        description: Play a Sound
        usage: /play-a-sound soundName
    #NOT SUPPORTED IN GLOWSTONE 1.8
    name-cow:
            description: Creates a Cow and Give it a name
            usage: /name-cow name
    who-am-i:
        description: Player info
        usage: /who-am-i
version: 0.1
