name: Bukkit Showcase

author: Toto Castaldi
website: https://github.com/toto-castaldi/bukkit-plugin-showcase
main: it.toto.minecraft.plugin.ShowCase

commands:
    build-a-cube:
        description: Build a Cube
        usage: /build-a-cube width height

version: 0.1
