name: gerard

author: Gerard
website:
main: it.gerard.minecraft.plugin.CoderDojoPlugin

commands:
    gerard-hello-world:
        description: Say HELLO !
        usage: /gerard-hello-world

    name-pig:
            description: Creates a Pig and Give it a             usage: /name-pig namev
name         
    name-spider:
            description: Creates a Spider and Give it a             usage: /name-spider name
name        
    name-wolf:
            description: Creates a Wolf and Give it a             usage: /name-wolf name
name     
    name-sheep:
            description: Creates a Sheep and Give it a             usage: /name-sheep name
name     
    name-horse:
            description: Creates a Sheep and Give it a             usage: /name-horse name

name     
    buildahouse:
            description: Creates a 10x5 glass house
            usage: /buildahouse


version: 0.1
