name: ludovico

author: Ludovico Castaldi
website: https://github.com/giacomo-castaldi
main: it.giacomo.minecraft.plugin.CoderDojoPlugin

commands:
    giacomo-hello-world:
        description: Say HELLO !
        usage: /ludovico-hello-world
version: 0.1
